package com.project.knowledgeassistant.services;



import com.project.knowledgeassistant.DTOs.ProcessedDocument;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

@Service
public class DocumentConversionService {

    @Value("${libreoffice.executable}")
    private String libreOfficeExecutable;

    public ProcessedDocument convertToPdf(Path inputFile, Path outputDirectory) {

        try {
            // Create output directory if it doesn't exist
            Files.createDirectories(outputDirectory);

            System.out.println("Creating directory: " + outputDirectory);

            ProcessBuilder processBuilder = new ProcessBuilder(
                    libreOfficeExecutable,
                    "--headless",
                    "--convert-to", "pdf",
                    "--outdir", outputDirectory.toString(),
                    inputFile.toString()
            );

            // Merge error stream with normal output
            processBuilder.redirectErrorStream(true);

            Process process = processBuilder.start();

            // Wait for LibreOffice to finish
            int exitCode = process.waitFor();

            if (exitCode != 0) {
                throw new RuntimeException(
                        "LibreOffice conversion failed for file: "
                                + inputFile.getFileName()
                );
            }

            // LibreOffice keeps the same filename but changes extension to .pdf
            String fileName = inputFile.getFileName().toString();

            int extensionIndex = fileName.lastIndexOf('.');

            String pdfFileName;

            if (extensionIndex > 0) {
                pdfFileName = fileName.substring(0, extensionIndex) + ".pdf";
            } else {
                pdfFileName = fileName + ".pdf";
            }

            Path pdfPath = outputDirectory.resolve(pdfFileName);

            ProcessedDocument processedDocument = new ProcessedDocument();
            processedDocument.setProcessedFileName(fileName);
            processedDocument.setProcessedFilePath(pdfPath);
            processedDocument.setProcessedFileType("application/pdf");

            if (!Files.exists(pdfPath)) {
                throw new RuntimeException(
                        "PDF was not generated by LibreOffice: " + pdfPath
                );
            }




            return processedDocument;

        } catch (IOException e) {

            throw new RuntimeException(
                    "Error while converting file to PDF: "
                            + inputFile.getFileName(),
                    e
            );

        } catch (InterruptedException e) {

            Thread.currentThread().interrupt();

            throw new RuntimeException(
                    "PDF conversion process was interrupted",
                    e
            );
        }
    }
}
