spring.application.name=KnowledgeAssistant

# ===== Neon Database =====
server.port = 8081

spring.datasource.url=jdbc:postgresql://ep-shy-lab-b5afowu2-pooler.c-7.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_vmsK3axj5tPz&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vmsK3axj5tPz
spring.datasource.driver-class-name=org.postgresql.Driver

#--JPA--
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Spring AI pgvector configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

# Upload directory (relative to project root)
app.upload.dir=uploads

# ===== Temporarily disable Spring AI auto-config (Day 2) =====
spring.ai.model.chat=none
spring.ai.model.embedding=none
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none

spring.ai.vectorstore.type=none
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

secret=${JWT_SECRET:ezsrdxtcfyvg12334456geuwfd!@#$%^&CFgvhbjnkml$ER%T&Y*UGCVHBJK12345r@#$%^&fcgv}