spring.application.name=KnowledgeAssistant

# ===== Neon Database =====
server.port = 8081

spring.datasource.url=jdbc:postgresql://ep-shy-lab-b5afowu2-pooler.c-7.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_vmsK3axj5tPz&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vmsK3axj5tPz
spring.datasource.driver-class-name=org.postgresql.Driver

#--JPA--
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

secret=${JWT_SECRET:ezsrdxtcfyvg12334456geuwfd!@#$%^&CFgvhbjnkml$ER%T&Y*UGCVHBJK12345r@#$%^&fcgv}

# Spring AI pgvector configuration

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.schema-name=public



spring.ai.model.chat=google-genai

spring.ai.google.genai.api-key=${GEMINI_API_KEY:dfghjkl;uyt}

#spring.ai.google.genai.chat.options.model=gemini-3.8-flash

spring.ai.google.genai.chat.options.model=gemini-3.5-flash-lite

spring.ai.google.genai.chat.temperature=0.2


# Upload directory (relative to project root)
app.upload.dir=uploads
app.file-storage.path=uploads/original
file.processed-dir=uploads/processed



secret=${JWT_SECRET:ezsrdxtcfyvg12334456geuwfd!@#$%^&CFgvhbjnkml$ER%T&Y*UGCVHBJK12345r@#$%^&fcgv}
jwt.secret=${JWT_SECRET:ezsrdxtcfyvg12334456geuwfd!@#$%^&CFgvhbjnkml$ER%T&Y*UGCVHBJK12345r@#$%^&fcgv}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000


# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=mxbai-embed-large

libreoffice.executable=C:/Program Files/LibreOffice/program/soffice.exe