spring.application.name=KnowledgeAssistant

server.port = 8081

spring.datasource.url=jdbc:postgresql://ep-shy-lab-b5afowu2-pooler.c-7.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_vmsK3axj5tPz&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vmsK3axj5tPz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

secret = ${dvshfown$%$$^$@#$%^&*()(*&^&*()DFGHJKLLKJHGFGHL:"jdjfd;k;jdfghjsfkgnb@###$$%^DXFCHGHJ:KLJHJHwaesuyttre@#$%%^&(**&^%rtfglk&yihgt(*&^%$easrtygj^&ugfdfhjklmjhft*igfhjkkjyyihjvhvss$%^&*(}
